apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: monitoring-app
  name: monitoring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-app
  template:
    metadata:
      labels:
        app: monitoring-app
    spec:
      containers:
      - image: rgera0901/monitoring-app:v1.14
        name: monitoring-app
        ports: 
        - containerPort: 80
