apiVersion: v1
kind: Service
metadata:
  labels:
    app: monitoring-app
  name: monitoring-app-svc
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: monitoring-app
  type: NodePort
