apiVersion: v1
kind: Service
metadata:
  labels:
    app: monitoring-app
  name: monitoring-app-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31000
  selector:
    app: monitoring-app
  type: NodePort
